#!/bin/sh
unread=$(notmuch search tag:unread | wc -l)
if [[ $unread -gt 0 ]];then
    notify-send -a Mutt -i ~/.local/share/icons/mail-$NOTMUCH_PROFILE.ico "New mail on $NOTMUCH_PROFILE" "$unread new emails"
fi

