#!/bin/sh
unread=$(notmuch search tag:unread | wc -l)
tmp=/tmp/id-$NOTMUCH_PROFILE
mid=1
if [[ $unread -gt 0 ]];then
    if [ -f "$tmp" ]; then
        mid=$(cat $tmp)
    fi
    mid=$(notify-send.py \
        -a Mutt \
        -r $mid \
        -i ~/.local/share/icons/mail-$NOTMUCH_PROFILE.ico \
        "New mail on $NOTMUCH_PROFILE" \
        "$unread new emails")
    echo $mid > $tmp
fi

